### ISSUE TITLE
整体进度

### ISSUE THREAD

**Issue by wizardforcel** [apachecn/stats-thinking-21-zh#1]
| 章节 | 贡献者 | 进度 | 奖励 |
| --- | --- | --- | --- |
| [零、前言](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/00.md) | @liuyixi520  | 完成 | 完成 |
| [一、引言](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/01.md) | @liuyixi520  | 完成 | 完成 |
| [二、处理数据](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/02.md) | @liuyixi520  | 完成 | 完成 |
| [三、概率](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/03.md) | @liuyixi520  | 完成 |  完成|
| [四、汇总数据](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/04.md) | @liuyixi520  | 完成 | 完成 |
| [五、将模型拟合到数据](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/05.md) | @liuyixi520  | 完成 | 完成 |
| [六、数据可视化](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/06.md) | @liuyixi520 | 完成 | 完成 |
| [七、采样](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/07.md) | @liuyixi520 | 完成 | 完成 |
| [八、重新采样和模拟](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/08.md) | @liuyixi520 | 完成 | 完成 |
| [九、假设检验](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/09.md) | @liuyixi520 | 完成 | 完成 |
| [十、置信区间、效应大小和统计功率](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/10.md) | @liuyixi520 | 完成 | 完成 |
| [十一、贝叶斯统计](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/11.md) |  @liuyixi520 | 完成 | 完成 |
| [十二、分类关系建模](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/12.md) |  @liuyixi520 | 完成 | 完成 |
| [十三、建模持续关系](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/13.md) | @liuyixi520  | 完成 | 完成 |
| [十四、一般线性模型](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/14.md) |  @liuyixi520 | 完成 | 完成 |
| [十五、比较方法](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/15.md) |  @liuyixi520 | 完成 | 完成 |
| [十六、统计建模过程：一个实例](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/16.md) |  @liuyixi520 | 完成 | 完成 |
| [十七、做重复性研究](https://github.com/apachecn/stats-thinking-21-zh/blob/master/docs/17.md) |  @liuyixi520 | 完成 | 完成 |

**Comment by liuyixi520** [comment]
我来翻译1-5章

**Comment by wizardforcel** [comment]
> @liuyixi520 我来翻译1-5章

ok。留下联系方式，否则无法发放奖励。

**Comment by liuyixi520** [comment]
> > @liuyixi520 我来翻译1-5章
> 
> ok。留下联系方式，否则无法发放奖励。

qq:1786410853

**Comment by liuyixi520** [comment]
我来翻译6-10章

**Comment by liuyixi520** [comment]
领取第十章到第十七章
