### ISSUE TITLE
机翻的和英文好像不是一个版本的书

### ISSUE THREAD

**Issue by liuyixi520** [apachecn/stats-thinking-21-zh#3]
请问这本书的英文原版是这个库么：https://github.com/statsthinking21/statsthinking21-core.git
我发现机翻的中文版和这个库的英文书好像不是一个版本。
比如说在第0章中，英文原版的的前两段在机翻中就没有：
The goal of this book is to the tell the story of statistics as it is used today by researchers around the world...
The book is also written in the wake of the reproducibility crisis that has engulfed many areas of science since 2010...
而且在翻译到第0章中的第四段时，机翻明显没有把英文版中的这句话翻译出来
I also tailored this book for the 10-week quarter system that we use at Stanford, which provides less time than the 16-week semester that most statistical textbooks are built for.

**Comment by wizardforcel** [comment]
可能英文版版本更新了，需要补上。
